// Membership Action Types
export const FETCH_MEMBERS_REQUEST = 'FETCH_MEMBERS_REQUEST';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_FAILURE = 'FETCH_MEMBERS_FAILURE';

export const ADD_MEMBER_REQUEST = 'ADD_MEMBER_REQUEST';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_FAILURE = 'ADD_MEMBER_FAILURE';

export const UPDATE_MEMBER_REQUEST = 'UPDATE_MEMBER_REQUEST';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';
export const UPDATE_MEMBER_FAILURE = 'UPDATE_MEMBER_FAILURE';

export const DELETE_MEMBER_REQUEST = 'DELETE_MEMBER_REQUEST';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_FAILURE = 'DELETE_MEMBER_FAILURE';

// Commission Action Types & Filters
export const FETCH_COMMISSIONS_REQUEST = 'FETCH_COMMISSIONS_REQUEST';
export const FETCH_COMMISSIONS_SUCCESS = 'FETCH_COMMISSIONS_SUCCESS';
export const FETCH_COMMISSIONS_FAILURE = 'FETCH_COMMISSIONS_FAILURE';
export const SET_COMMISSION_FILTERS = 'SET_COMMISSION_FILTERS';
export const RESET_COMMISSION_FILTERS = 'RESET_COMMISSION_FILTERS';

// Membership Commission Engine Action Types
export const GENERATE_MEMBERSHIP_COMMISSIONS_REQUEST = 'GENERATE_MEMBERSHIP_COMMISSIONS_REQUEST';
export const GENERATE_MEMBERSHIP_COMMISSIONS_SUCCESS = 'GENERATE_MEMBERSHIP_COMMISSIONS_SUCCESS';
export const GENERATE_MEMBERSHIP_COMMISSIONS_FAILURE = 'GENERATE_MEMBERSHIP_COMMISSIONS_FAILURE';
export const UPDATE_COMMISSION_STRATEGY_RULES = 'UPDATE_COMMISSION_STRATEGY_RULES';
export const RESET_COMMISSION_STRATEGY_RULES = 'RESET_COMMISSION_STRATEGY_RULES';
export const CLEAR_COMMISSION_ENGINE_LOGS = 'CLEAR_COMMISSION_ENGINE_LOGS';
export const TOGGLE_COMMISSION_DEDUCTIONS = 'TOGGLE_COMMISSION_DEDUCTIONS';

export const FETCH_TDS_STATUS_REQUEST = 'FETCH_TDS_STATUS_REQUEST';
export const FETCH_TDS_STATUS_SUCCESS = 'FETCH_TDS_STATUS_SUCCESS';
export const FETCH_TDS_STATUS_FAILURE = 'FETCH_TDS_STATUS_FAILURE';

export const SAVE_TDS_STATUS_REQUEST = 'SAVE_TDS_STATUS_REQUEST';
export const SAVE_TDS_STATUS_SUCCESS = 'SAVE_TDS_STATUS_SUCCESS';
export const SAVE_TDS_STATUS_FAILURE = 'SAVE_TDS_STATUS_FAILURE';

export const FETCH_COMMISSION_CONFIGS_REQUEST = 'FETCH_COMMISSION_CONFIGS_REQUEST';
export const FETCH_COMMISSION_CONFIGS_SUCCESS = 'FETCH_COMMISSION_CONFIGS_SUCCESS';
export const FETCH_COMMISSION_CONFIGS_FAILURE = 'FETCH_COMMISSION_CONFIGS_FAILURE';

export const SAVE_MEMBERSHIP_CONFIG_REQUEST = 'SAVE_MEMBERSHIP_CONFIG_REQUEST';
export const SAVE_MEMBERSHIP_CONFIG_SUCCESS = 'SAVE_MEMBERSHIP_CONFIG_SUCCESS';
export const SAVE_MEMBERSHIP_CONFIG_FAILURE = 'SAVE_MEMBERSHIP_CONFIG_FAILURE';

export const SAVE_REPURCHASE_CONFIG_REQUEST = 'SAVE_REPURCHASE_CONFIG_REQUEST';
export const SAVE_REPURCHASE_CONFIG_SUCCESS = 'SAVE_REPURCHASE_CONFIG_SUCCESS';
export const SAVE_REPURCHASE_CONFIG_FAILURE = 'SAVE_REPURCHASE_CONFIG_FAILURE';

// Repurchase Commission Engine Action Types
export const GENERATE_REPURCHASE_COMMISSIONS_REQUEST = 'GENERATE_REPURCHASE_COMMISSIONS_REQUEST';
export const GENERATE_REPURCHASE_COMMISSIONS_SUCCESS = 'GENERATE_REPURCHASE_COMMISSIONS_SUCCESS';
export const GENERATE_REPURCHASE_COMMISSIONS_FAILURE = 'GENERATE_REPURCHASE_COMMISSIONS_FAILURE';
export const UPDATE_REPURCHASE_STRATEGY_RULES = 'UPDATE_REPURCHASE_STRATEGY_RULES';
export const RESET_REPURCHASE_STRATEGY_RULES = 'RESET_REPURCHASE_STRATEGY_RULES';
export const CLEAR_REPURCHASE_ENGINE_LOGS = 'CLEAR_REPURCHASE_ENGINE_LOGS';


// Auth & Profile Action Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const CHECK_AUTH_SESSION = 'CHECK_AUTH_SESSION';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const CLEAR_PROFILE_STATUS = 'CLEAR_PROFILE_STATUS';

// Repurchase Action Types & Filters
export const FETCH_REPURCHASES_REQUEST = 'FETCH_REPURCHASES_REQUEST';
export const FETCH_REPURCHASES_SUCCESS = 'FETCH_REPURCHASES_SUCCESS';
export const FETCH_REPURCHASES_FAILURE = 'FETCH_REPURCHASES_FAILURE';

export const ADD_REPURCHASE_REQUEST = 'ADD_REPURCHASE_REQUEST';
export const ADD_REPURCHASE_SUCCESS = 'ADD_REPURCHASE_SUCCESS';
export const ADD_REPURCHASE_FAILURE = 'ADD_REPURCHASE_FAILURE';
export const SET_REPURCHASE_FILTERS = 'SET_REPURCHASE_FILTERS';
export const RESET_REPURCHASE_FILTERS = 'RESET_REPURCHASE_FILTERS';

// Payout Action Types & Filters
export const FETCH_PAYOUTS_REQUEST = 'FETCH_PAYOUTS_REQUEST';
export const FETCH_PAYOUTS_SUCCESS = 'FETCH_PAYOUTS_SUCCESS';
export const FETCH_PAYOUTS_FAILURE = 'FETCH_PAYOUTS_FAILURE';

export const PROCESS_PAYOUT_REQUEST = 'PROCESS_PAYOUT_REQUEST';
export const PROCESS_PAYOUT_SUCCESS = 'PROCESS_PAYOUT_SUCCESS';
export const PROCESS_PAYOUT_FAILURE = 'PROCESS_PAYOUT_FAILURE';

export const BATCH_PROCESS_PAYOUTS_REQUEST = 'BATCH_PROCESS_PAYOUTS_REQUEST';
export const BATCH_PROCESS_PAYOUTS_SUCCESS = 'BATCH_PROCESS_PAYOUTS_SUCCESS';
export const BATCH_PROCESS_PAYOUTS_FAILURE = 'BATCH_PROCESS_PAYOUTS_FAILURE';
export const SET_PAYOUT_FILTERS = 'SET_PAYOUT_FILTERS';
export const RESET_PAYOUT_FILTERS = 'RESET_PAYOUT_FILTERS';
